spring:
  # MySQL setting
  datasource:
    # ip, username, password will change
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://asrai-app-backend-database.cwk2ukisdzzj.ap-northeast-2.rds.amazonaws.com:13386/joinit?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: adminasrai
    password: joinit!!asrai


  jpa:
    # JPA query check
    show-sql: true
    # When defining DDL (create, alter, drop), the unique functions of the DB can be used.
    hibernate:
      ddl-auto: update
    # Improves the readability of SQL generated while Hibernate is running.
    properties:
      hibernate:
        format_sql: true
      open-in-view: true

server:
  port: 80
  servlet:
    context-path: /

logging:
  level:
    web: debug